/*
 * generated by Xtext 2.12.0
 */
package fr.n7.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PDL2ProposalProvider extends AbstractPDL2ProposalProvider {
}
