/*
 * generated by Xtext 2.12.0
 */
package fr.n7


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PDL2StandaloneSetup extends PDL2StandaloneSetupGenerated {

	def static void doSetup() {
		new PDL2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
