/**
 * generated by Xtext 2.12.0
 */
package fr.n7.ide;

import fr.n7.ide.AbstractPDL2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PDL2IdeModule extends AbstractPDL2IdeModule {
}
